Cam wp7 task4
Mikolaj-A-Kowalski/openmc pull request #2
Opened 2020-03-11 18:50 UTC by Mikolaj-A-Kowalski

This is intended as an internal review for the task 4. It implements what was outlined in Issue #1505. 

Following functionality was implemented
* Exception is raised if the volume of a Cell is set to -ve value 
* For a cell filled with material or distributed materials, ``Cell.atoms`` method calculates total number of atoms in all instances of a cell. 

@simondrichards before you do any review I would like to @ChasingNeutrons  to have a look through the changes and correct my grammar/spelling so you don't have to do this this time.

2020-03-11 19:54 UTC, simondrichards commented
Thanks @Mikolaj-A-Kowalski, I will wait for @ChasingNeutrons to review first.

2020-03-16 13:40 UTC, ChasingNeutrons commented on openmc/cell.py
> +        # (sice volume has just changed)
That should be:
`# (since volume has just changed)`

2020-03-16 14:00 UTC, ChasingNeutrons reviewed
One or two spelling mistakes, a few inconsistent capitalisations, otherwise looks good to me.

2020-03-16 14:00 UTC, ChasingNeutrons commented on openmc/cell.py
> +        # (sice volume has just changed)
That should be:
` # (since volume has just changed)`

2020-03-16 14:00 UTC, ChasingNeutrons commented on openmc/cell.py
> +                msg = 'Cannot calculate atoms content becouse no volume '\
Would modify ever so slightly to:
`msg = 'Cannot calculate atom content because no volume '\
                      'is set. Use Cell.volume to provide it or perform '\
                      'a stochastic volume calculation.'`

2020-03-16 14:00 UTC, ChasingNeutrons commented on openmc/cell.py
> +                      'materials. Atoms content must be calculated with '\
Replace this line with: 
`'materials. Atom content must be calculated with '\`

2020-03-16 14:00 UTC, ChasingNeutrons commented on openmc/cell.py
> +                # Get atomic Densities
Remove capitalisation such that we have:
`# Get atomic densities`

2020-03-16 14:00 UTC, ChasingNeutrons commented on openmc/cell.py
> +        # Info about atoms content can now be invalid
Likewise:
`# Info about atom content can now be invalid`

2020-03-16 14:00 UTC, ChasingNeutrons commented on openmc/cell.py
> +        # Print Volume only when its set to avoid breaking regression
Remove capitalisation and correct its:
`# Print volume only when it is set to avoid breaking regression`

2020-03-16 14:00 UTC, ChasingNeutrons commented on openmc/cell.py
> +                msg = ('Cell is filled with void. It contains no atoms. '
`msg = ('Cell is filled with void. It contains no atoms. '
                       'Material must be set to calculate atom content.')`

2020-03-16 14:00 UTC, ChasingNeutrons commented on openmc/cell.py
> +                msg = ('Cannot calculate atoms content becouse no volume '
`msg = ('Cannot calculate atoms content because no volume '
                       'is set. Use Cell.volume to provide it or perform '
                       'a stochastic volume calculation.')`

2020-03-16 14:00 UTC, ChasingNeutrons commented on openmc/cell.py
> +                       'contain multiple materials. Atoms content must be '
`'contain multiple materials. Atom content must be '`

2020-03-16 14:00 UTC, ChasingNeutrons commented on openmc/cell.py
> +            # we need special treatment for UFloat input
`# We need special treatment for UFloat input`

2020-03-16 14:00 UTC, ChasingNeutrons commented on tests/unit_tests/test_cell.py
> +    # Empty cell with Volume
`# Empty cell with volume`

2020-03-16 14:00 UTC, ChasingNeutrons commented on tests/unit_tests/test_cell.py
> +    # Empty cell with Uncertain Volume
` # Empty cell with uncertain volume`

2020-03-16 14:00 UTC, ChasingNeutrons commented on tests/unit_tests/test_cell.py
> +    # Material Cell with no Volume
`# Material Cell with no volume`

2020-03-16 14:00 UTC, ChasingNeutrons commented on tests/unit_tests/test_cell.py
> +    # Cell with volume but with Void fill
`# Cell with volume but with void fill`

2020-03-16 14:00 UTC, ChasingNeutrons commented on openmc/cell.py
> +            Dictionary which keys are nuclides and values the number of atoms.
`Dictionary in which keys are nuclides and values the number of atoms.`

2020-03-16 14:00 UTC, ChasingNeutrons commented on openmc/cell.py
> +                msg = ('Universe and Lattice cells can contain multiple '
`msg = ('Universe and Lattice cells can contain multiple '
                       'materials in different proportions. Atom content must '
                       'be calculated with stochastic volume calculation')`

2020-03-16 14:36 UTC, Mikolaj-A-Kowalski commented
The latest commit should address all comments by @ChasingNeutrons. I think it is good for a the full internal review by @simondrichards .

2020-03-17 11:39 UTC, simondrichards requested changes
Thanks @Mikolaj-A-Kowalski and @ChasingNeutrons,

Looks good. Just a few minor changes requested.

2020-03-17 11:39 UTC, simondrichards commented on openmc/cell.py
> +        it is a total volume of all instances.
```suggestion
        it is the total volume of all instances.
```

2020-03-17 11:39 UTC, simondrichards commented on openmc/cell.py
> +        in the cell, or all its instances for 'sdistribmat' fill. For example,
```suggestion
        Mapping of nuclides to the total number of atoms for each nuclide present
        in the cell, or in all of its instances for a 'distribmat' fill. For example,
```

2020-03-17 11:39 UTC, simondrichards commented on docs/source/usersguide/geometry.rst
> +calculation::
```suggestion
If the total volume occupied by all instances of a cell in the geometry is known
by the user, it is possible to assign this volume to a cell without performing a stochastic volume
calculation::
```

2020-03-17 11:39 UTC, simondrichards commented on docs/source/usersguide/geometry.rst
> +of a cell (e.g. ``{'H1':1.0e22, 'O16':0.5e22, ...}``)::
```suggestion
Once a volume is set, and a cell is filled with a material or distributed
materials, it is possible to use the :func:`~openmc.Cell.atoms` method to obtain
a dictionary of nuclides and their total number of atoms in all instances
of a cell (e.g. ``{'H1':1.0e22, 'O16':0.5e22, ...}``)::
```

2020-03-17 18:59 UTC, Mikolaj-A-Kowalski commented
Thank you for you comments @simondrichards ! I will not close this pull request and issue one for the openmc repository.

2020-03-17 18:59 UTC, closed without merging